export const COMPOSE_EMAIL_REQUEST = "COMPOSE_EMAIL_REQUEST";
export const COMPOSE_EMAIL_SUCCESS = "COMPOSE_EMAIL_SUCCESS";
export const COMPOSE_EMAIL_FAILURE = "COMPOSE_EMAIL_FAILURE";
export const CLEAR_COMPOSE_EMAIL_MESSAGE = "CLEAR_COMPOSE_EMAIL_MESSAGE";
